export default {
  dropdownTriangle: require('../assets/images/ic_dropdown.png'),
  fb: require('../assets/images/ic_facebook.png'),
  apple: require('../assets/images/ic_apple.png'),
  google: require('../assets/images/ic_google.png'),
  insta: require('../assets/images/ic_insta.png'),
  back: require('../assets/images/ic_back.png'),
  backWithSquare: require('../assets/images/backWithSquare.png'),
  rightBlue: require('../assets/images/ic_goA.png'),
  rangoli: require('../assets/images/125-1250916_white-mandala-png.png'),
  dp: require('../assets/images/photo.jpg'),
  search: require('../assets/images/loupe.png'),
  mail: require('../assets/images/conversation.png'),
  logo: require('../assets/images/kisspng-paytm-logo-brand-service-product-funding-archives-letusdiscuss-com-5b6d395a2f19a3.3321178815338847621929.png'),
  payLogo: require('../assets/images/pay.png'),
  addedImage: require('../assets/images/AddedMoney.png'),
  plusLogo: require('../assets/images/Health+care.png'),
  card: require('../assets/images/ezgif.com-webp-to-png.png'),
};
